/**
 * This file is autogenerated. Do not edit it manually.
 */
import { type Abi } from 'viem';

export const signatureVerifierAbi = [
  {
    inputs: [
      { internalType: 'address', name: 'expectedSigner', type: 'address' },
      { internalType: 'bytes32', name: 'messageHash', type: 'bytes32' },
      { internalType: 'bytes', name: 'signature', type: 'bytes' },
    ],
    name: 'verifySignature',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const satisfies Abi;
