# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "trust-ethos-web-testnet"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[deploy]
  strategy = 'canary'

[env]
  ECHO_INTERNAL_BASE_URL = "http://trust-ethos-echo-testnet.internal:8080"
  NEXT_PUBLIC_ECHO_BASE_URL = "https://api.testnet.ethos.network"
  NEXT_PUBLIC_ETHOS_ENV = "testnet"
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    soft_limit = 500

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/api/healthcheck"

[[vm]]
  cpu_kind = "performance"
  cpus = 4
  memory_mb = 16384
