// This file is a copy of
// https://github.com/ant-design/nextjs-registry/blob/main/src/AntdRegistry.tsx
// with minor modification to solve this issue
// https://github.com/ant-design/cssinjs/issues/195
// Once the issue is resolved, we should get back at using AntdRegistry from
// @ant-design/nextjs-registry package.

'use client';

import {
  createCache,
  extractStyle,
  StyleProvider,
  type StyleProviderProps,
} from '@ant-design/cssinjs';
import { useServerInsertedHTML } from 'next/navigation';
import { useMemo, useRef } from 'react';

type AntdRegistryProps = Omit<StyleProviderProps, 'cache'>;

export function AntdRegistry(props: AntdRegistryProps) {
  const cache = useMemo(() => createCache(), []);
  const inserted = useRef(false);

  useServerInsertedHTML(() => {
    if (inserted.current) {
      return null;
    }

    inserted.current = true;

    let styleText = extractStyle(cache, { plain: true });

    // The modified line
    // When we use some antd components, sometimes the extracted style from
    // cache gets broken because it contains and extra "@layer antd".
    // Replacing it manually here before inserting to the DOM.
    styleText = styleText.replaceAll(/@layer antd@layer antd/g, '@layer antd');

    return (
      <style
        id="antd-cssinjs"
        // to make sure this style is inserted before Ant Design's style generated by client
        data-rc-order="prepend"
        data-rc-priority="-1000"
        dangerouslySetInnerHTML={{ __html: styleText }}
      />
    );
  });

  return <StyleProvider {...props} cache={cache} />;
}
