.git
.github
.husky
.vitest
vitest.config.ts
.vscode
scripts
test-reports
.cache
.DS_Store
.cache
.editorconfig
.elasticsearch
.eslintignore
.eslintrc.json
.gitignore
.kibana
.logstash
.nvmrc
.prettierrc
.solhint.json
README.md
compose.yml
knip.json
node_modules
serve.json
Dockerfile.dockerignore
Dockerfile
README.md


services/web
services/rabbitmq
standalone


/public/build
/build
